name: DAST
on: 
    workflow_dispatch: {}

jobs:
  dast-nuclei:
    name: DAST - Nuclei
    runs-on: ubuntu-latest

    steps:
    - name: Nuclei - Vulnerability Scan
      id: nuclei_scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: http://143.198.140.208:4000
        templates: .nuclei
        user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
        flags: '-sf nodegoat-secret.yaml -ps -u  -var username=${{ secrets.NUCLEI_USER }} -var password=${{ secrets.NUCLEI_PASSWORD }}'

    - name: GitHub Workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuclei.log
        path: nuclei.log