name: Trufflehog

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown